### ISSUE TITLE
The Button icon for "Omemo encryption is activated and authenticated" is counter-intutive

### ISSUE THREAD

**Issue by cromulentbanana** [kalkin/gajim-omemo#135]
#### General information

Before opening an issue, please read our Wiki
- **Gajim Version:** eg 0.16.5
- **Plugin Version:** eg 0.9.5
- **OS:** eg Ubuntu 16.10
#### Steps to reproduce

![image](https://cloud.githubusercontent.com/assets/1322972/19600273/9840c8e4-97a4-11e6-9c22-75f9e708d0b5.png)

1 The button (as included in a screen capture above) has a red bar. Red bars usually are associated with errors or warnings.
#### Expected result

I would expect that the icon that explains that omemo is working should be a closed lock icon (for example, similar to the icon that is used in the android Conversations.im client)
#### Debug output

Please start Gajim with `-l gajim.plugin-system.omemo=DEBUG` and post the log file

**Comment by lovetox** [comment]
i agree, though that is the API and symbol Gajim offers to Plugins its not something OMEMO chooses.

also with one symbol you cant correctly show the status of a chat.
every chat message could have different properties, one could be send in plaintext, the next encrypted.

also the icon could change if you have other plugins activated like GPG or OTR.
OMEMO can not control the icons state at all time, so it might be incorrectly set.

right now gajim doesnt offer something better, like per chat line icon that shows us what the properties of a specific message was.

so i close this because from a plugin perspective we will not change that.

though im a dev for gajim also, and i let you know that this is on our list, to give a better indication of the properties of a message.

if you want you can open a ticket on trac.gajim.org about it, i doubt though that it will make things faster. Gajim has to few devs at the moment for fast, bigger changes.
