### ISSUE TITLE
Use a secure storage for OMEMO keys

### ISSUE THREAD

**Issue by akallabeth** [kalkin/gajim-omemo#2]
I just found your nice plugin for gajim and tested a bit.
Looks really promising (working nicely so far), but what I did not like is that the OMEMO keys are stored as part of the local configuration.
Using something like `python-keyring` to store the keys in the most secure location for the specific platform would certainly be a good idea.

Don't know if it is already on your todo, just some feedback ;)

**Comment by kalkin** [comment]
Thank you for your feedback. Generally at the moment there are other issues more important, like implementing the key trust model.

As far as I understand, python-keyring saves your data somewhere (depending on your os) encrypted. I still have two questions:
- How does python-keyring make sure, that only the authorized app (in this case Gajim) is requesting the password for your keyring?
- How does python-keyring prevent any other running X app from just key logging your secret during entering? (See [this for more info on GUI Isolation](http://theinvisiblethings.blogspot.in/2011/04/linux-security-circus-on-gui-isolation.html))

I'm not convinced yet if you are not better off with full disc encryption and custom SELinux rules for Gajim and its config directory.

**Comment by akallabeth** [comment]
You have quite strong points with authorization and the lack of X in regard to isolation.
Full disc encryption and SELinux is also the better way but sadly currently its not there yet (I don't know any linux distro where this is not quite some work to get it running smooth)
So the only benefit (currently) would be sensitive information encrypted on disk even without full disc encryption.
As for the others, authorization and isolation is up to the backend (which sadly libsecret currently does not provide) and X11 lacks.

**Comment by kalkin** [comment]
> Full disc encryption and SELinux is also the better way but sadly currently its not there yet (I don't know any linux distro where this is not quite some work to get it running smooth)

Full disk encryption can be enabled when you are installing almost any Linux Distribution. This is not an issue.

About SELinux: Centos 7 and Fedora have SELinux enabled by default, I think others use it also. You just do not notice it, because most GUI programms are missing SELinux profiles.  Creating an SELinux profile for Gajim (and contributing it to the main branch) would be a great improvement!

I would be interested about the benefits which python-keyring brings to Windows/MacOSX. I would not be surprised if, we assume Windows/MacOSX as our TCB, if they have a way of making sure only authorized apps can get access to keychain. (AFAIK this is one of the features KDbus will bring to linux).

@akallabeth Generally my time is limited, but I'am very interested in SELinux profile for Gajim and using python-keyring on other operating systems.  If you want to make any research in this direction I would be very grateful!

**Comment by akallabeth** [comment]
@kalkin You are right about full disc encryption (I actually use it, but was not clear enough in my last post), the point was more with SELinux. I'm well aware that it is enabled by default in the red hat / fedora world, but they have quite permissive profiles (to my knowledge, is ~3 fedora versions old), so that basically every application with access to the home directory can read / modify files there. (would be interesting to protect `.config` et al with more specific rules)

But the main point of python-keyring would be the following:
- No configuration required and the data is at least encrypted (full disc encryption has to be set up and the main point of OMEMO over OTR is ease of use)
- With systems where access protection is enforced (Mac OS currently) the access is limited to the creating application. (SELinux could actually also be used to protect libsecret from what I read on their project)
- Application separation is a separate issue, but to my knowledge wayland will fix a lot in that area.

About windows/macOS:
- Mac OS X checks the hash signature of the calling application and asks for access to the keychain, so there this would actually help. Keyboard events are not that easily captured as with X11, but I don't know how well that is actually implemented.
- Windows is just using the session credentials to encrypt the data (so basically the same as libsecret). So no help against applications querying the data and are running as the same user. Application separation is partly available (there is always the issue with `SetWindowHookEx` grabbing all keyboard input)

As for time, I'm currently a bit busy, but this will change again in about a month, so I hope I can provide some code for keyring support after that ;)

**Comment by kalkin** [comment]
> I'm well aware that it is enabled by default in the red hat / fedora world, but they have quite permissive profiles (to my knowledge, is ~3 fedora versions old), so that basically every application with access to the home directory can read / modify files there. 

I think this is an issue with desktop apps, because there're over 9000 of them and no one wants to create a profile for each one. :smile: 

> (would be interesting to protect .config et al with more specific rules)

Yes this is exactly what I meant. 

> As for time, I'm currently a bit busy, but this will change again in about a month, so I hope I can provide some code for keyring support after that ;)

This would be awesome. I think the best way would be to introduce it to Gajim and create some kind of API so all plugins (like OTR or just storing of passwords) could use it. I would extend _gajim-omemo_ to use such an API. Feel free to open an issue at at [Gajim Trac](https://trac.gajim.org/wiki/HowToCreateATicket)

 IMHO you get more bang for buck  by creating  a SELinux policy which allows only Gajim to access `config/gajim` this is faster implemented and merged in to main Gajim repo, as something as 'major' as introducing `python-keyring`.

**Comment by kalkin** [comment]
I close this issue for now, feel free to reopen it when you made some progress.
