### ISSUE TITLE
Can't open OMEMO encrypted files

### ISSUE THREAD

**Issue by syntafin** [kalkin/gajim-omemo#76]
Today I saw, that files that send with enabled OMEMO encryption over http-upload, can't shown on PC/Tablet.

**Comment by lovetox** [comment]
this is correct, as a workaround disable omemo befor you send with http upload to a device which is not conversations.
the issue is already discussed here:
https://github.com/omemo/gajim-omemo/issues/19

in this thread there are various other ways described how you can open the files

there will be an update to the http upload plugin which lets you see the files in the near future
