### ISSUE TITLE
[UX] When undecided, force fingerprint verification

### ISSUE THREAD

**Issue by dllud** [kalkin/gajim-omemo#94]
Current behaviour:
1. User installs and activates OMEMO plugin.
2. User opens a chat with a contact that has a OMEMO fingerprint.
3. Contact fingerprint is undecided: OMEMO plugin is automatically turned off and shows the warning `OMEMO encryption disabled`.
4. User does not read/understand the warning.
5. User unwittingly sends plaintext messages with sensitive info.

The behaviour implemented in Conversations seems superior as it avoids this mistake:
1. User opens a chat with a contact that has a OMEMO fingerprint: OMEMO is automatically enabled.
2. User tries to send a message: Conversations asks for fingerprint verification before sending it.
In order to send a plaintext message, the user would have to go back and manually select "Unencrypted" in the encryption dropdown.

I feel the "verification before sending first message" is the way to go. If the user has taken trouble to install and activate OMEMO plugin it probably means they wanna use it whenever possible. It makes sense to avoid plaintext messages at all cost.

Could you implement the Conversation's behaviour with a pop-up window?

**Comment by lovetox** [comment]
hi,
you have misconception about what it means to activate omemo

activating the omemo plugin in the plugin manager of gajim, doesnt activate encryption for all contacts.
so the message `OMEMO encryption disabled` doesnt mean encryption was turned on befor, it just reflects the current state of encryption.

receiving fingerprints, verifing fingerprints doesnt do anything to the state of the encryption (if its turned on or off)

to activate the encryption you have to click the OMEMO button (orange fish symbol) and click activate.
if you activated OMEMO and have no trusted fingerprints, you cant send messages and a information message is printed to the chat why you cant send messages. in no way is it every turned off without user interaction (clicking the button) !

i understand that coming from conversations you maybe thought that encryption is enabled automatically for every contact that supports it, but that was not always so (its a change made fairly recently to conversations, and its in no way the obvious correct behavior for everyone)

i will let this open anyway because the popup is on the TODO list
also i will think about activating omemo automatically when you receive the very first fingerprint from a contact (means omemo is supported)

**Comment by lovetox** [comment]
though i remember now that there was a UI bug which is fixed in current HEAD but not pushed as new version, where it would show you in Chat `OMEMO encryption disabled` and the checkbox of the omemo button was checked (as when it would be activated)

can you remember, did you send the first message, or your contact?

**Comment by dllud** [comment]
Thanks for the explanation.

> you have misconception about what it means to activate omemo
> activating the omemo plugin in the plugin manager of gajim, doesnt activate encryption for all contacts.

Exactly. This happened to a few non-tech people  on my contact list. They expected the opposite: encryption to be enabled for all once the plugin was activated.
I believe this misconception will keep repeating itself. Thus the right way to go is just what you suggested above:

> activating omemo automatically when you receive the very first fingerprint from a contact

Then show the popup asking for verification on their first message ;).

**Comment by dllud** [comment]
> where it would show you in Chat OMEMO encryption disabled and the checkbox of the omemo button was checked

That actually happened to me once. But since the warning message was there I didn't gave much thought to it.

The real problem though as to do with the users' misconception about the default encryption state as discussed above.

**Comment by lovetox** [comment]
i think i solved all these problems in version 0.8
should be a much smoother experience now.
new version will be pushed to gajim on the weekend.

if you still notice problems please report them here, i close this until then.

thanks for your report.
